apiVersion: apps/v1
kind: Deployment
metadata:
  name: ryzen-me
  namespace: ryzen-me
  labels:
    app: ryzen-me
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryzen-me
  template:
    metadata:
      labels:
        app: ryzen-me
    spec:
      imagePullSecrets:
        - name: harborpullsecret
      containers:
      - name: website
        image: harbor.ryzen.me/library/ryzen.me:latest
        ports:
        - containerPort: 80
          protocol: TCP
